<a href="https://colab.research.google.com/github/HunRajveer/Statistics-/blob/main/Chi_SquareTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:

import numpy as np
import seaborn as sns
import pandas as pd
from scipy import stats

In [9]:
df=sns.load_dataset('titanic')

In [10]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [11]:
df['sex'],df['survived'].dropna()

(0        male
 1      female
 2      female
 3      female
 4        male
         ...
 886      male
 887    female
 888    female
 889      male
 890      male
 Name: sex, Length: 891, dtype: object,
 0      0
 1      1
 2      1
 3      1
 4      0
       ..
 886    0
 887    1
 888    0
 889    1
 890    0
 Name: survived, Length: 891, dtype: int64)

In [12]:
# our motive is to peform a chi square test in qualitative data (sex) and check wether it holds a relation with survived

In [13]:
frame = pd.crosstab(df.survived,df.sex)

In [14]:
frame

sex       female  male
survived
0             81   468
1            233   109

In [15]:
# when we peform chi test it returns 4value in tuple forms so assign it we need to pass four variable
chi,p_value,dof,expected = stats.chi2_contingency(frame)
# chi2_contingency is the name for chi-square test

In [16]:
chi

np.float64(260.71702016732104)

In [17]:
dof

1

In [18]:
p_value
# result np.float64(1.1973570627755645e-58) means power mai -58 very very small value

np.float64(1.1973570627755645e-58)

In [19]:
expected

array([[193.47474747, 355.52525253],
       [120.52525253, 221.47474747]])

In [21]:
# to give final-verdict we will compare p_value with signifence value
alpha=0.05
if p_value<alpha:
  print("null hypothises is rejected and there is a signifance relation between sex and survived")
else:
    print("there is no relationship between survervied and sex")

null hypothises is rejected and there is a signifance relation between sex and survived